### Вычисления с помощью Numpy

#### Задание 1

In [1]:
import numpy as np

In [5]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

#### Задание 2

a_centered = a - mean_a

In [10]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

In [20]:
print(f'{a_centered[:, 0]}\n{a_centered[:, 1]}')

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]


In [22]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [30]:
a_centered_sp

8.0

In [51]:
a_ucs = a_centered_sp / (a.shape[0] - 1)
a_ucs

2.0

#### Задание 4

In [43]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [45]:
at = a.T
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [52]:
a_check = np.cov(at)[0, 1]
a_check

2.0

In [54]:
a_ucs == a_check

True